trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist/deerlicious'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactMasterDirectory)/drop_fr_master.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactMasterDirectory)'
    ArtifactName: 'drop_fr_master'
    publishLocation: 'Container'


